apiVersion: v1
kind: ConfigMap
metadata:
  name: sqlink-backend-config
  labels:
    app: sqlink-backend
data:
  ASPNETCORE_URLS: http://+:8080
  ASPNETCORE_ENVIRONMENT: Production
  Logging__LogLevel__Default: Information
  Logging__LogLevel__Microsoft.AspNetCore: Warning
